services:
  - type: web
    name: bapgpt-condominios
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ORGANIZATION_ID
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000 